{{ if eq .Values.profile "dist" }}
{{- if .Values.gateway.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    {{ include "gateway.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.gateway.replicas }}
  strategy:
  {{- with .Values.gateway.updateStrategy }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "gateway.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{ include "gateway.labels" . | nindent 8 }}
        {{- with .Values.gateway.additionalLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- if .Values.gateway.additionalAnnotations -}}
      annotations:
        {{- with .Values.gateway.additionalAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
    spec:
      containers:
      - image: {{ .Values.gateway.image.repository }}:{{ .Values.gateway.image.tag }}
        {{- if .Values.springArgs.overrideSpringArgs }}
        env:
          - name: spring_args
            value: {{ .Values.springArgs.value }}
        {{- end }}
        imagePullPolicy: {{ .Values.gateway.image.pullPolicy }}
        name: {{ include "gateway.fullname" . }}
        ports:
        - containerPort: 9090
          protocol: TCP
        lifecycle:
           preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - curl -X PUT "http://{{ .Values.eureka.hostname }}:{{ .Values.eureka.port }}/eureka/apps/GATEWAY/$HOSTNAME:gateway:9090/status?value=OUT_OF_SERVICE"
        

        resources:
{{ toYaml .Values.gateway.resources | indent 10 }}
      restartPolicy: {{ .Values.gateway.restartPolicy }}
      {{- if .Values.gateway.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.gateway.serviceAccount.name }}
      {{- end }}
      securityContext: {{ .Values.gateway.securityContext | toYaml }}
      terminationGracePeriodSeconds: {{ .Values.gateway.terminationGracePeriodSeconds }}
{{- end }}
{{- end }}
