{{- if .Values.subscriptionManager.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "subscriptionManager.fullname" . }}
  labels:
    {{ include "subscriptionManager.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.subscriptionManager.replicas }}
  strategy:
  {{- with .Values.subscriptionManager.updateStrategy }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "subscriptionManager.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{ include "subscriptionManager.labels" . | nindent 8 }}
        {{- with .Values.subscriptionManager.additionalLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- if .Values.subscriptionManager.additionalAnnotations -}}
      annotations:
        {{- with .Values.subscriptionManager.additionalAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
    spec:
      containers:
        {{- if eq .Values.profile "dist"}}
      - image: {{ .Values.subscriptionManager.image.repository }}:{{ .Values.subscriptionManager.image.tag }}
        {{ else }}
      - image: {{ .Values.subscriptionManager.image.repository }}:{{ .Values.subscriptionManager.image.no_eureka_tag }}
        {{ end }}
        {{- if .Values.springArgs.overrideSpringArgs }}
        env:
          - name: spring_args
            value: {{ .Values.springArgs.value }}
        {{- end }}
        imagePullPolicy: {{ .Values.subscriptionManager.image.pullPolicy }}
        name: {{ include "subscriptionManager.fullname" . }}
        ports:
        - containerPort: 2027
          protocol: TCP
        {{- if eq .Values.profile "dist"}}
        lifecycle:
           preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - curl -X PUT "http://{{ .Values.eureka.hostname }}:{{ .Values.eureka.port }}/eureka/apps/SUBSCRIPTION-MANAGER/$HOSTNAME:subscription-manager:2026/status?value=OUT_OF_SERVICE"
        {{ end }}
        
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 2027
          initialDelaySeconds: {{ .Values.subscriptionManager.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.subscriptionManager.readinessProbe.periodSeconds }}
          successThreshold: {{ .Values.subscriptionManager.readinessProbe.successThreshold }}
         
      
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 2027
          initialDelaySeconds: {{ .Values.subscriptionManager.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.subscriptionManager.livenessProbe.periodSeconds }}
          successThreshold: {{ .Values.subscriptionManager.livenessProbe.successThreshold }}
            
        resources:
{{ toYaml .Values.subscriptionManager.resources | indent 10 }}
      restartPolicy: {{ .Values.subscriptionManager.restartPolicy }}
      {{- if .Values.subscriptionManager.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.subscriptionManager.serviceAccount.name }}
      {{- end }}
      securityContext: {{ .Values.subscriptionManager.securityContext | toYaml }}
      terminationGracePeriodSeconds: {{ .Values.subscriptionManager.terminationGracePeriodSeconds }}
{{- end }}

