server:
  port: 2025

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

bootstrap:
  servers: kafka:9092


  
spring:
  kafka:
    consumer:
      bootstrap-servers: kafka:9092
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092

