mysettings:
  application-name: aio-runner
  kafka:
    bootstrap:
      host: ${bushost:localhost}
      port: ${busport:9092}
  postgres:
    host: ${dbhost:localhost}
    port: ${dbport:5432}
    username: ${dbuser:ngb}
    password: ${dbpass:ngb}
    database-name: ${dbname:ngb}
  gateway:
    host: ${gateway.host:localhost}
    port: ${gateway.port:9090}
atcontext:
  url: http://${mysettings.gateway.host}:${mysettings.gateway.port}/ngsi-ld/contextes/
bootstrap:
  servers: ${mysettings.kafka.bootstrap.host}:${mysettings.kafka.bootstrap.port}
jdbcurl: jdbc:postgresql://${mysettings.postgres.host}:${mysettings.postgres.port}/${mysettings.postgres.database-name}?ApplicationName=${mysettings.application-name}

kafka:
  replytimeout: 10000
management:
  endpoint:
    restart:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  application.name: ${mysettings.application-name}
  kafka:
    producer:
      bootstrap-servers: ${bootstrap.servers}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers: ${bootstrap.servers}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: eu.neclab.ngsildbroker.commons.datatypes,eu.neclab.ngsildbroker.commons.datatypes.requests
    admin:
      properties:
        cleanup:
          policy: compact
  security:
    mode: deactivated
#-------For mode header to provide Bearer Token------------------
#    oauth2:
#      resourceserver:
#        jwt:
#          jwk-set-uri: http://localhost:8080/realms/scorpio/protocol/openid-connect/certs
#          issuer-uri: http://localhost:8080/realms/scorpio
#-------For mode webauth to get web login------------------
#      client:
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:8080/realms/scorpio
#        registration:
#          keycloak-client:
#            provider: keycloak
#            client-id: scorpio1
#            client-secret: 12SNKt2ORNXASHJRU6bZ0IkKoMu0WS5M
#            authorization_grant_type: client_credentials
#          keycloak:
#            client-id: scorpio1
#            client-secret: 12SNKt2ORNXASHJRU6bZ0IkKoMu0WS5M
  datasource:
    hikari:
      connectionTimeout: 30000
      idleTimeout: 30000
      maxLifetime: 2000000
      maximumPoolSize: 16
      minimumIdle: 2
      poolName: SpringBootHikariCP
    password: ${mysettings.postgres.password}
    url: ${jdbcurl}
    username: ${mysettings.postgres.username}
  flyway:
    baselineOnMigrate: true
    connect-retries: 10
    connect-retries-interval: 2
  main:
    lazy-initialization: false
    allow-bean-definition-overriding: true
    allow-circular-references: true
# Increase the Hystrix timeout to 60s (globally)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
server:
  port: 9090
  tomcat:
    relaxed-path-chars: <,>,[,\,],^,`,{,|,}
    relaxed-query-chars: <,>,[,\,],^,`,{,|,}
    max:
      threads:200
selfhostcorecontext: http://localhost:9090/corecontext
logging:
  level:
    root: INFO
    eu.neclab.ngsildbroker: INFO
    org.apache.kafka: ERROR
    org.spring.kafka: ERROR
    org.springframework.kafka: ERROR
    #com.zaxxer.hikari: ERROR
ngsild:
  corecontext: https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.3.jsonld
scorpio:
  tenants: 
     default:
        poolmax: -1
        idlemin: -1
#     test555:
#        poolmax: 20
#        idlemin: 15
  gatewayurl: null
  fedbrokers: null
  cors: 
    enable: true
    allowall: true
  directDB: true
  history:
    autorecording: notactive
    max-limit: 1000
    default-limit: 50
    batch-operations:
      create:
        max: 1000
      upsert:
        max: 1000
      update:
        max: 1000
      delete:
        max: 1000
      query:
        max: 1000
  entity:
    max-limit: 1000
    default-limit: 50
    batch-operations:
      create:
        max: 1000
      upsert:
        max: 1000
      update:
        max: 1000
      delete:
        max: 1000
      query:
        max: 1000
  registry:
    max-limit: 1000
    default-limit: 50
#    autoregmode: attributes
    autorecording: notactive
    batch-operations:
      create:
        max: 1000
      upsert:
        max: 1000
      update:
        max: 1000
      delete:
        max: 1000
      query:
        max: 1000
  sync:
    announcement-time: 200
    check-time: 1000
  topics:
    entity: ENTITY
    registry: REGISTRY
    temporal: TEMPORAL
    internalnotification: I_NOTIFY
    internalregsub: I_REGSUB
    regsubsync: REG_SUB_SYNC
    subsync: SUB_SYNC
    regsubalive: REG_SUB_ALIVE
    subalive: SUB_ALIVE