mysettings:
  application-name: aio-runner
  kafka:
    bootstrap:
      host: ${bushost:localhost}
      port: ${busport:9092}
  postgres:
    host: ${dbhost:localhost}
    port: ${dbport:5432}
    username: ${dbuser:ngb}
    password: ${dbpass:ngb}
    database-name: ${dbname:ngb}
  gateway:
    host: ${gateway.host:localhost}
    port: ${gateway.port:9090}
atcontext:
  url: http://${mysettings.gateway.host}:${mysettings.gateway.port}/ngsi-ld/contextes/
bootstrap:
  servers: ${mysettings.kafka.bootstrap.host}:${mysettings.kafka.bootstrap.port}
jdbcurl: jdbc:postgresql://${mysettings.postgres.host}:${mysettings.postgres.port}/${mysettings.postgres.database-name}?ApplicationName=${mysettings.application-name}
broker:
  id: FedBroker1
  parent:
    location:
      url: SELF

batchoperations:
  maxnumber:
    create: 1000
    update: 1000
    upsert: 1000
    delete: 1000
defaultLimit: 50 
kafka:
  replytimeout: 10000
management:
  endpoint:
    restart:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  application.name: ${mysettings.application-name}
  kafka:
    producer:
      bootstrap-servers: ${bootstrap.servers}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers: ${bootstrap.servers}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: eu.neclab.ngsildbroker.commons.datatypes,eu.neclab.ngsildbroker.commons.datatypes.requests
    admin:
      properties:
        cleanup:
          policy: compact
  security:
    active: false
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: https://idp.example.com/auth/realms/demo
#      client:
#        provider:
#          keycloak:
#            issuer-uri: https://idp.example.com/auth/realms/demo
#        registration:
#          keycloak-client:
#            provider: keycloak
#            client-id: spring-security
#            client-secret: 6cea952f-10d0-4d00-ac79-cc865820dc2c
#            authorization_grant_type: client_credentials
#          keycloak:
#            client-id: spring-security
#            client-secret: 6cea952f-10d0-4d00-ac79-cc865820dc2c
  datasource:
    hikari:
      connectionTimeout: 30000
      idleTimeout: 30000
      maxLifetime: 2000000
      maximumPoolSize: 20
      minimumIdle: 5
      poolName: SpringBootHikariCP
    password: ${mysettings.postgres.password}
    url: ${jdbcurl}
    username: ${mysettings.postgres.username}
  flyway:
    baselineOnMigrate: true
    connect-retries: 10
    connect-retries-interval: 2
  main:
    lazy-initialization: false
    allow-bean-definition-overriding: true
    allow-circular-references: true
# Increase the Hystrix timeout to 60s (globally)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
server:
  port: 9090
  tomcat:
    relaxed-path-chars: <,>,[,\,],^,`,{,|,}
    relaxed-query-chars: <,>,[,\,],^,`,{,|,}
    max:
      threads:200
selfhostcorecontext: http://localhost:9090/corecontext
logging:
  level:
    root: INFO
    eu.neclab.ngsildbroker: DEBUG
    org.apache.kafka: ERROR
    org.spring.kafka: ERROR
    org.springframework.kafka: ERROR
    #com.zaxxer.hikari: ERROR
ngsild:
  corecontext: https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.3.jsonld
scorpio:
  directDB: true
  history:
    autorecording: notactive
    max-limit: 1000
    default-limit: 50
    batch-operations:
      create:
        max: 1000
      upsert:
        max: 1000
      update:
        max: 1000
      delete:
        max: 1000
      query:
        max: 1000
  entity:
    max-limit: 1000
    default-limit: 50
    batch-operations:
      create:
        max: 1000
      upsert:
        max: 1000
      update:
        max: 1000
      delete:
        max: 1000
      query:
        max: 1000
  registry:
    max-limit: 1000
    default-limit: 50
    autorecording: notactive
    batch-operations:
      create:
        max: 1000
      upsert:
        max: 1000
      update:
        max: 1000
      delete:
        max: 1000
      query:
        max: 1000
  topics:
    entity: ENTITY
    registry: REGISTRY
    temporal: TEMPORAL
    internalnotification: I_NOTIFY
    internalregsub: I_REGSUB