{{- if eq .Values.profile "dist" }}
{{- if .Values.configServer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "configServer.fullname" . }}
  labels:
    {{- include "configServer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.configServer.replicas }}
  strategy:
  {{- with .Values.configServer.updateStrategy }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "configServer.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{ include "configServer.labels" . | nindent 8 }}
        {{- with .Values.configServer.additionalLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- if .Values.configServer.additionalAnnotations -}}
      annotations:
        {{- with .Values.configServer.additionalAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
    spec:
      containers:
      - image: {{ .Values.configServer.image.repository }}:{{ .Values.configServer.image.tag }}
        {{- if .Values.springArgs.overrideSpringArgs }}
        env:
          - name: spring_args
            value: {{ .Values.springArgs.value }}
        {{- end }}
        imagePullPolicy: {{ .Values.configServer.image.pullPolicy }}
        name: {{ include "configServer.fullname" . }}
        ports:
        - containerPort: 8888
          protocol: TCP
        lifecycle:
           preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - curl -X PUT "http://{{ .Values.eureka.hostname }}:{{ .Values.eureka.port }}eureka/apps/CONFIGSERVER/$HOSTNAME:configserver:8888/status?value=OUT_OF_SERVICE"
        
        resources:
{{ toYaml .Values.configServer.resources | indent 10 }}
      restartPolicy: {{ .Values.configServer.restartPolicy }}
      {{- if .Values.configServer.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.configServer.serviceAccount.name }}
      {{- end }}
      securityContext: {{ .Values.configServer.securityContext | toYaml }}
      terminationGracePeriodSeconds: {{ .Values.configServer.terminationGracePeriodSeconds }}
{{- end }}
{{- end }}
